---
- name: CIS Hardening for Ubuntu 24.04
  hosts: all
  become: yes
  tasks:
    # Kernel modules
    - name: Ensure cramfs kernel module is not available
      command: modprobe -r cramfs
      ignore_errors: yes

    - name: Ensure freevxfs kernel module is not available
      command: modprobe -r freevxfs
      ignore_errors: yes

    - name: Ensure hfs kernel module is not available
      command: modprobe -r hfs
      ignore_errors: yes

    - name: Ensure hfsplus kernel module is not available
      command: modprobe -r hfsplus
      ignore_errors: yes

    - name: Ensure jffs2 kernel module is not available
      command: modprobe -r jffs2
      ignore_errors: yes

    - name: Ensure overlayfs kernel module is not available
      command: modprobe -r overlayfs
      ignore_errors: yes

    - name: Ensure squashfs kernel module is not available
      command: modprobe -r squashfs
      ignore_errors: yes

    - name: Ensure udf kernel module is not available
      command: modprobe -r udf
      ignore_errors: yes

    - name: Ensure usb-storage kernel module is not available
      command: modprobe -r usb-storage
      ignore_errors: yes

    - name: Ensure unused filesystems kernel modules are not available
      command: modprobe -r <module_name>  # Vervang <module_name> door ongebruikte modules
      ignore_errors: yes

    # Partitioning and mount options
    - name: Ensure /tmp is a separate partition
      command: mount | grep '/tmp'
      register: tmp_partition
      failed_when: tmp_partition.stdout == ""

    - name: Ensure nodev option set on /tmp partition
      mount:
        path: /tmp
        fstype: tmpfs
        opts: nodev,nosuid,noexec
        state: mounted

    - name: Ensure /dev/shm is a separate partition
      command: mount | grep '/dev/shm'
      register: shm_partition
      failed_when: shm_partition.stdout == ""

    - name: Ensure nodev option set on /dev/shm partition
      mount:
        path: /dev/shm
        fstype: tmpfs
        opts: nodev,nosuid,noexec
        state: mounted

    - name: Ensure separate partition exists for /home
      command: mount | grep '/home'
      register: home_partition
      failed_when: home_partition.stdout == ""

    - name: Ensure nodev option set on /home partition
      mount:
        path: /home
        opts: nodev
        state: mounted

    - name: Ensure separate partition exists for /var
      command: mount | grep '/var'
      register: var_partition
      failed_when: var_partition.stdout == ""

    - name: Ensure nodev option set on /var partition
      mount:
        path: /var
        opts: nodev
        state: mounted

    - name: Ensure separate partition exists for /var/tmp
      command: mount | grep '/var/tmp'
      register: var_tmp_partition
      failed_when: var_tmp_partition.stdout == ""

    - name: Ensure nodev option set on /var/tmp partition
      mount:
        path: /var/tmp
        opts: nodev,nosuid,noexec
        state: mounted

    - name: Ensure separate partition exists for /var/log
      command: mount | grep '/var/log'
      register: var_log_partition
      failed_when: var_log_partition.stdout == ""

    - name: Ensure nodev option set on /var/log partition
      mount:
        path: /var/log
        opts: nodev,nosuid,noexec
        state: mounted

    - name: Ensure separate partition exists for /var/log/audit
      command: mount | grep '/var/log/audit'
      register: var_log_audit_partition
      failed_when: var_log_audit_partition.stdout == ""

    - name: Ensure nodev option set on /var/log/audit partition
      mount:
        path: /var/log/audit
        opts: nodev,nosuid,noexec
        state: mounted

    # GPG keys and package manager
    - name: Ensure GPG keys are configured
      command: apt-key list

    - name: Ensure package manager repositories are configured
      command: cat /etc/apt/sources.list

   
