---
- name: CIS Hardening for Ubuntu 24.04
  hosts: all
  become: yes
  tasks:
    # Kernel modules
    - name: Ensure cramfs kernel module is not available
      command: modprobe -r cramfs
      ignore_errors: yes

    - name: Ensure freevxfs kernel module is not available
      command: modprobe -r freevxfs
      ignore_errors: yes

    - name: Ensure hfs kernel module is not available
      command: modprobe -r hfs
      ignore_errors: yes

    - name: Ensure hfsplus kernel module is not available
      command: modprobe -r hfsplus
      ignore_errors: yes

    - name: Ensure jffs2 kernel module is not available
      command: modprobe -r jffs2
      ignore_errors: yes

    - name: Ensure overlayfs kernel module is not available
      command: modprobe -r overlayfs
      ignore_errors: yes

    - name: Ensure squashfs kernel module is not available
      command: modprobe -r squashfs
      ignore_errors: yes

    - name: Ensure udf kernel module is not available
      command: modprobe -r udf
      ignore_errors: yes

    - name: Ensure usb-storage kernel module is not available
      command: modprobe -r usb-storage
      ignore_errors: yes

    

    - name: Ensure separate partition exists for /home
      command: mount | grep '/home'
      register: home_partition
      failed_when: home_partition.stdout == ""

   
    # GPG keys and package manager
    - name: Ensure GPG keys are configured
      command: apt-key list

    - name: Ensure package manager repositories are configured
      command: cat /etc/apt/sources.list

   
